// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCunMoco36GuMXaYZHRTKEOT5m1Rr2QY',
    appId: '1:516388712035:web:394dbaa5afbc0b11b39256',
    messagingSenderId: '516388712035',
    projectId: 'office-project-eaf6a',
    authDomain: 'office-project-eaf6a.firebaseapp.com',
    storageBucket: 'office-project-eaf6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWF8GAO4T14QewN0Hk8pAGvrUKKly2ydc',
    appId: '1:516388712035:android:c966237cf9e6ab31b39256',
    messagingSenderId: '516388712035',
    projectId: 'office-project-eaf6a',
    storageBucket: 'office-project-eaf6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8D-ILFRWBUtOhstxiWFG0rdHxuAP3pwY',
    appId: '1:516388712035:ios:755eda5578e2379db39256',
    messagingSenderId: '516388712035',
    projectId: 'office-project-eaf6a',
    storageBucket: 'office-project-eaf6a.firebasestorage.app',
    iosBundleId: 'com.example.newfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8D-ILFRWBUtOhstxiWFG0rdHxuAP3pwY',
    appId: '1:516388712035:ios:755eda5578e2379db39256',
    messagingSenderId: '516388712035',
    projectId: 'office-project-eaf6a',
    storageBucket: 'office-project-eaf6a.firebasestorage.app',
    iosBundleId: 'com.example.newfirebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCunMoco36GuMXaYZHRTKEOT5m1Rr2QY',
    appId: '1:516388712035:web:a63c79a5175beb05b39256',
    messagingSenderId: '516388712035',
    projectId: 'office-project-eaf6a',
    authDomain: 'office-project-eaf6a.firebaseapp.com',
    storageBucket: 'office-project-eaf6a.firebasestorage.app',
  );
}
